In [1]:
even=[2, 4, 6, 8, 10]
even[0]

2

In [2]:
even=[2, 4, 6, 8, 10]
even[0:2]

[2, 4]

In [3]:
even=[2, 4, 6, 8, 10]
even[3:]

[8, 10]

In [5]:
import pandas as pd
import numpy as np
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
             [[11, 12, 13], [14, 15, 16], [17, 18, 19],],
             [[21, 22, 23], [24, 25, 26], [27, 28, 29]]])
print(x[1,1])
print(x[:,1,1])
print(x[1,:,1])

[14 15 16]
[ 5 15 25]
[12 15 18]


In [13]:
import pandas as pd
import numpy as np
x = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
             [11, 12, 13, 14, 15]])
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])