In [1]:
import numpy as np
dataset = np.array([[2, 4, 6, 8, 3, 2, 5],
                    [7, 5, 3, 1, 6, 8, 0],
                    [1, 3, 2, 1, 0, 0, 8]])
print(np.max(dataset, axis=1)-np.min(dataset, axis=1))

[6 8 8]


In [2]:
import numpy as np
a = np.array([1, 2, 3])
a = a*2
print(a)

[2 4 6]


In [4]:
import numpy as np
a = np.array([[1, 0],
             [0, 1]])
b = np.array([[4, 7],
             [1, 7]])
c = np.dot(a, b)
print(c)

[[4 7]
 [1 7]]


In [1]:
import pandas as pd
import numpy as np
x = np.array([[ 8,  42,  35, 8],
             [13,  39,  39, 41],
             [20,  17,  5, 24]]) 
y = x.T
print(y)

[[ 8 13 20]
 [42 39 17]
 [35 39  5]
 [ 8 41 24]]
